[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
# codeforlife = {ref = "v0.1.12", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
# whitenoise = "==6.5.0"
django = "==3.2.19"
django-countries = "==7.3.1"
djangorestframework = "==3.13.1"
django-pipeline = "==2.0.8"
django-recaptcha = "==2.0.6"
pyyaml = "==5.4.1"
importlib-metadata = "==4.13.0"
rapid-router = ">=4"
aimmo = ">=2"
reportlab = "==3.6.13"
django-formtools = "==2.2"
django-otp = "==1.0.2"  # we needed to fix this due to a wide ranged dependency in django-two-factor-auth
requests = "==2.31.0"
django-treebeard = "==4.3.1"
django-sekizai = "==2.0.0"
django-classy-tags = "==2.0.0"
sqlparse = "==0.4.4"
libsass = "==0.22.0"
phonenumbers = "==8.12.12"
more-itertools = "==8.7.0"
cfl-common = "==6.32.0"
django-ratelimit = "==3.0.1"
django-preventconcurrentlogins = "==0.8.2"
django-csp = "==3.7"
setuptools = "==62.1.0"  # upgrading this causes an error when publishing the cfl_common package to PyPI for some reason see https://github.com/ocadotechnology/codeforlife-portal/actions/runs/3883963564/jobs/6625894054
django-import-export = "*"
google-python-cloud-debugger = "==2.*"
google-cloud-logging = "==1.*"
google-auth = "==1.*"
google-cloud-container = "==2.3.0"
"django-anymail[amazon_ses]" = "==7.0.*"

[dev-packages]
django-selenium-clean = "==0.3.3"
django-test-migrations = "==1.2.0"
responses = "==0.18.0"
selenium = "==3.141.0"
snapshottest = "==0.6.0"
pytest-django = "==4.5.2"
pytest = "==7.*"
django-import-export = "*"
pytest-cov = "*"
pytest-xdist = "*"
pytest-order = "*"
pyvirtualdisplay = "*"
pytest-mock = "*"
PyPDF2 = "==2.10.6"
black = "*"

[requires]
python_version = "3.8"
